services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5431:5431"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=sssadmin
      - DB_PASSWORD=ssspassword
      - DB_NAME=supershoppingservice
    command: ["npm", "start"]

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: supershoppingservice
      POSTGRES_USER: sssadmin
      POSTGRES_PASSWORD: ssspassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
