services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5431:5431"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=sssadmin
      - DB_PASSWORD=ssspassword
      - DB_NAME=supershoppingservice
    networks:
      - app-network
  
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: supershoppingservice
      POSTGRES_USER: sssadmin
      POSTGRES_PASSWORD: ssspassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: